
title: Moroti Adegboyega
description: "Emerging Engineer — Robotics, AI, Sensors, Community, Passion"

theme: jekyll-theme-Architect

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://olumorotiadegboyega.github.io"

author:
  name: "Moroti Adegboyega"
  email: "olu.360moroti@gmail.com"
social:
  links:
    - https://www.linkedin.com/in/moroti-adegboyega-a35527313/
    - https://github.com/OlumorotiAdegboyega/
